# Generated by Django 3.2.10 on 2022-01-09 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220109_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nutrition',
            old_name='drinks',
            new_name='drink',
        ),
    ]
